---
volumes:
  nexus-data: {}

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    restart: always
    ports:
      - "8081:8081"
      - "8085:8085"
    volumes:
      - nexus-data:/sonatype-work